# Generated by Django 3.1.7 on 2021-03-04 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bank", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="is_deleted",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="is_deleted",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_deleted",
        ),
        migrations.AddField(
            model_name="account",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
