# Generated by Django 3.1.7 on 2021-03-04 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bank", "0002_auto_20210304_0718"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="account_number",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="account",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
